export const SECTOR_MAP = {
  'RELIANCE.NS': 'Energy',
  'TCS.NS': 'IT',
  'HDFCBANK.NS': 'Banking',
  'INFY.NS': 'IT',
  'ICICIBANK.NS': 'Banking',
  'HINDUNILVR.NS': 'FMCG',
  'SBIN.NS': 'Banking',
  'BHARTIARTL.NS': 'Telecom',
  'WIPRO.NS': 'IT',
  'KOTAKBANK.NS': 'Banking',
  'AXISBANK.NS': 'Banking',
  'HCLTECH.NS': 'IT',
  'ASIANPAINT.NS': 'FMCG',
  'MARUTI.NS': 'Auto',
  'TATAMOTORS.NS': 'Auto',
  'TATASTEEL.NS': 'Metals',
  'SUNPHARMA.NS': 'Pharma',
  'DRREDDY.NS': 'Pharma',
  'POWERGRID.NS': 'Power',
  'NTPC.NS': 'Power',
  'ONGC.NS': 'Energy',
  'BAJFINANCE.NS': 'Finance',
  'BAJAJFINSV.NS': 'Finance',
  'TITAN.NS': 'Consumer',
  'ULTRACEMCO.NS': 'Cement',
  'NESTLEIND.NS': 'FMCG',
  'TECHM.NS': 'IT',
  'DIVISLAB.NS': 'Pharma',
  'GRASIM.NS': 'Cement',
  'ADANIENT.NS': 'Conglomerate',
}

export const SECTOR_COLORS = {
  'IT': '#8b5cf6',
  'Banking': '#3b82f6',
  'FMCG': '#22c55e',
  'Energy': '#f59e0b',
  'Telecom': '#ec4899',
  'Auto': '#f97316',
  'Metals': '#94a3b8',
  'Pharma': '#06b6d4',
  'Power': '#eab308',
  'Finance': '#6366f1',
  'Consumer': '#14b8a6',
  'Cement': '#a78bfa',
  'Conglomerate': '#fb923c',
  'Other': '#475569',
}

export const getSector = (symbol) => SECTOR_MAP[symbol] || 'Other'